### ISSUE TITLE
URL String formatting

### ISSUE THREAD

**Issue by Alperencode** [zscengiz/web-scraping#1]
[This](https://github.com/zscengiz/web-scraping/blame/c0183f0864f276d0aa7497deadaf4690e01d51a7/IMDB-Project/main.ipynb#L78) string should be: 
 
```python
new_link = 'https://www.imdb.com' + point.h3.a.get('href')\n"
# new_link = https://www.imdb.com/title/tt0111161/
```
Instead of:
```python
new_link = 'https://www.imdb.com/' + point.h3.a.get('href')\n"
# new_link = https://www.imdb.com//title/tt0111161/
```
Because `point.h3.a.get('href')` returns a link like `/title/tt0111161/`, there is no need to put another `/`. It doesn't cause any problem but creates a messy URL.

**Comment by zscengiz** [comment]
Thank you for bringing this to my attention. The issue has been fixed, and I'm closing it now.
